Makefile: Fix race condition affecting parallel builds
When using `make -j4` (or more than 4) to speed up builds by
running jobs in parallel, I sometimes get compilation error
like this one:

jedec.c: In function ‘write_jedec_file’:
jedec.c:311:40: error: ‘VERSION’ undeclared (first use in this function)
  311 |               STX, jedec->device_name, VERSION, jedec->QP, jedec->QF, jedec->F,
      |                                        ^~~~~~~
jedec.c:311:40: note: each undeclared identifier is reported only once for each function it appears in

That's because `version.h` is not fully written yet when
compiler reads the C files.

This commit addresses this issue by adding a dependency
on version header to all the object files. Implicit rule
is still used to compile them, so no recipe is needed.